##
# overriding aliases
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  alias dir='dir --color=auto'
  alias vdir='vdir --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

alias cp='cp -i'
alias su='su -l'
alias less='less -x 2'
alias gopen='gnome-open'
alias open='xdg-open'
alias ping='(figlet Miau || echo Miau) ; ping'
alias mv='mv -i'
##
# usefull commands, as aliases
alias cls='clear ; ls -h'
alias ll='ls -lh'
alias la='ls -Alh'
alias l='ls -CF'
alias ping8='ping 8.8.8.8'
alias pingg='ping www.google.com.br'
alias cls='clear && ls'
alias whereamirly='pwd -P'
alias whereami='pwd -L'
alias getlogo='screenfetch'
alias myip='hostname -I | cut -d" " -f 1'
alias myexip='curl "www.echoip.net" ; echo '
alias goreal='cd $(whereamirly)'

# Aliases only valid on MORDOR server
if [ $(hostname) = "MORDOR" ]; then
  # alias for java 8
  alias java8='/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java'
  alias javac8='/usr/lib/jvm/java-8-openjdk-amd64/bin/javac'
  alias jar8='/usr/lib/jvm/java-8-openjdk-amd64/bin/jar'
  # alias for java 7
  alias java7='/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java'
  alias javac7='/usr/lib/jvm/java-7-openjdk-amd64/bin/javac'
  alias jar7='/usr/lib/jvm/java-7-openjdk-amd64/bin/jar'
  # alias for java 6
  alias java6='/usr/lib/jvm/java-6-openjdk-amd64/jre/bin/java'
  alias javac6='/usr/lib/jvm/java-6-openjdk-amd64/bin/javac'
  alias jar6='/usr/lib/jvm/java-6-openjdk-amd64/bin/jar'

  # Alias definitions.
  # You may want to put all your additions ocult aliaes
  # ~/.bash_ocult_aliases, instead of adding them here directly.
  if [ -f ~/.bash_ocult_aliases ]; then
    . ~/.bash_ocult_aliases
  fi

elif [[ $(hostname) = "lups"* ]]; then
  alias open='xdg-open'
  alias gopen='gnome-open'
fi
