syntax on
set autoindent
set number
set numberwidth=1
set ignorecase
set shiftwidth=2
set tabstop=2
set expandtab
set list
" Attempt to determine the type of a file based on its name and possibly its
" contents. Use this to allow intelligent auto-indenting for each filetype,
" and for plugins that are filetype specific.
filetype indent plugin on
" nnoremap c d "
" BeginGuakeMode "
" nnoremap a h "
" nnoremap w k "
" nnoremap s j "
" nnoremap d l "
" EndGuakeMode "

